version: "3.8"
services:
     
    mongo:
        image: mongo
        mem_limit: 500M
        cpus: 1
        volumes: 
            - ./db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: distri
            MONGO_INITDB_ROOT_PASSWORD: secret
        expose:
            - "27017"
        networks:
            service-network:
                aliases:
                    - mongo
        
    back:
        build: ./api
        mem_limit: 500M
        cpus: 1
        environment: 
            MONGO_DB: mongo
            MONGO_USER: distri
            MONGO_PASS: secret
        expose:
            - "8082"
        depends_on: 
            - mongo
        networks:
            service-network:
                aliases:
                    - back

    nginx:
        image: nginx
        mem_limit: 500M
        cpus: 1
        volumes:
            - ./templates/nginxback.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - 4000:4000
        depends_on: 
            - back
        networks:
            service-network:
                aliases: 
                    - nginx

    nginxdb:
        image: nginx
        mem_limit: 500M
        cpus: 1
        volumes:
            - ./templates/nginxdb.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - 5000:5000
        depends_on: 
            - mongo
        networks:
            service-network:
                aliases: 
                    - nginxdb   
        

networks:
    service-network:
        name: service-net
        driver: bridge
        ipam:
            driver: default
