version: "3.8"
services: 
    mongo:
        image: mongo
        mem_limit: 500M
        cpus: 1
        volumes: 
            - ./db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: distri
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - 27017:27017
        networks:
            service-network:
                aliases:
                    - mongo
        
    back:
        build: ./api
        mem_limit: 500M
        cpus: 1
        environment: 
            MONGO_DB: mongo
            MONGO_USER: distri
            MONGO_PASS: secret
        depends_on: 
            - mongo
        networks:
            service-network:
                aliases:
                    - api

    nginx:
        image: nginx
        mem_limit: 500M
        cpus: 1
        volumes:
         - ./templates:/etc/nginx/templates
        ports:
         - "8080:80"
        environment:
            NGINX_HOST: api
            NGINX_PORT: 80
        networks:
            service-network:
                aliases: 
                    - nginx

networks:
    service-network:
        name: service-net
        driver: bridge
        ipam:
            driver: default
